Test trigger

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,8 +1,14 @@
 pipeline {
   agent any
 
+  options {
+    timestamps()
+    ansiColor('xterm')
+    buildDiscarder(logRotator(numToKeepStr: '10'))
+  }
+
   triggers {
-    githubPush()  // Trigger Jenkins on GitHub push
+    githubPush() // Trigger Jenkins on GitHub push
   }
 
   parameters {
@@ -14,15 +20,14 @@ pipeline {
     ECR_REPO = '636768524979.dkr.ecr.eu-central-2.amazonaws.com/lavanya-jenkins-repo'
     AWS_REGION = 'eu-central-2'
     CLUSTER_NAME = 'lavanya-test-cluster'
-    BRANCH_NAME = 'main'  // Static value for environment
+    BRANCH_NAME = 'main'
   }
 
   stages {
     stage('Checkout Code') {
       steps {
         script {
-          def branch = env.BRANCH_NAME ?: 'main'  // Dynamic logic here
-          git branch: branch, url: 'https://github.com/boyalavanya26/sample_try.git'
+          git branch: env.BRANCH_NAME, url: 'https://github.com/boyalavanya26/sample_try.git'
         }
       }
     }
@@ -75,6 +80,7 @@ pipeline {
         withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]) {
           script {
             def deploymentYaml = """
+# --- Kubernetes YAML ---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -200,7 +206,7 @@ spec:
             writeFile file: 'kube-deploy.yaml', text: deploymentYaml
             sh """
               aws eks update-kubeconfig --region ${env.AWS_REGION} --name ${env.CLUSTER_NAME}
-              kubectl apply -f kube-deploy.yaml
+              retry 3 kubectl apply -f kube-deploy.yaml
             """
           }
         }
@@ -211,8 +217,10 @@ spec:
       steps {
         script {
           sh '''
+          set +e
           kubectl run mongo-client --rm -i --image=mongo -- \
           mongosh "mongodb://speakease-mongo:27017" --eval 'db.getSiblingDB("authdb").users.find().limit(5).pretty()'
+          set -e
           '''
         }
       }
@@ -224,7 +232,7 @@ spec:
       echo "✅ Deployment and MongoDB automation successful!"
     }
     failure {
-      echo "❌ Deployment failed.Please check logs for details."
+      echo "❌ Deployment failed. Please check logs for details."
     }
   }
 }
